AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-dynamodb

  Sample SAM Template for sam-dynamodb
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMODB_URL: "https://8000-prashantaeg-dynamolearn-ighx8i5hkie.ws-us104.gitpod.io"

Resources:
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - 'POST'
          - 'GET'
          - 'PUT'
          - 'DELETE'
        AllowHeaders:
          - 'Content-Type'
        AllowOrigins:
          - '*'

  CreateProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: products-handlers/
      Handler: createProduct.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateProductApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: MyApi
            Path: /create-product
            Method: post
            Auth:
              Authorizer: NONE
          
    
  GetAllProductsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: products-handlers/
      Handler: getAllProducts.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GetAllProductsApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: MyApi
            Path: /get-all
            Method: get
    
  GetParticularProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: products-handlers/
      Handler: getParticularProduct.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GetParticularProductApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: MyApi
            Path: /get-particular/{productId}
            Method: get
    
  DeleteParticularProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: products-handlers/
      Handler: deleteParticularProduct.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteParticularProductApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: MyApi
            Path: /delete-particular/{productId}
            Method: delete

  MoveStocksFromWarehouseToShopFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: products-handlers/
      Handler: moveStocksFromWarehouseToShop.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        MoveStocksFromWarehouseToShopApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: MyApi
            Path: /movestock-w-s/{productId}/{stocksToMoveWS}
            Method: put
  
  MoveStocksFromShopToWarehouseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: products-handlers/
      Handler: moveStocksFromShopToWarehouse.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        MoveStocksFromShopToWarehouseApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: MyApi
            Path: /movestock-s-w/{productId}/{stocksToMoveSW}
            Method: put

  # CreateItemFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.createItem
  #     Runtime: nodejs18.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /create
  #           Method: post
  #           Auth:
  #             Authorizer: NONE

  # GetOneItemFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.getItem
  #     Runtime: nodejs18.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /get-one/{id}/{price}
  #           Method: get
  #           Auth:
  #             Authorizer: NONE

  # GetAllItemsFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.getAllItems
  #     Runtime: nodejs18.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /get-all
  #           Method: get
  
  # DeleteItemFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.deleteItem
  #     Runtime: nodejs18.x
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api
  #         Properties:
  #           Path: /delete/{id}/{price}
  #           Method: delete
  #           Auth:
  #             Authorizer: NONE


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
